<input type='number' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldClass() ?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo htmlspecialchars($this->getFieldValue()); ?>"
    <?php if (strlen($this->getMin())) echo "min=" . $this->getMin(); ?>
    <?php if (strlen($this->getMax())) echo "max=" . $this->getMax(); ?>
    <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>/>